apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deployment
  labels:
    app: catalogue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: catalogue:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80